name: Firestore Action

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  firestore:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/functions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd functions
        pip install --cache-dir ~/.cache/pip -r requirements.txt

    - name: Install Firebase CLI
      run: curl -sL https://firebase.tools | bash

    - name: Decode and Authenticate with Firebase
      env:
        FIREBASE_SERVICE_ACCOUNT_KEY_BASE64: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY_BASE64 }}
      run: |
        echo $FIREBASE_SERVICE_ACCOUNT_KEY_BASE64 | base64 --decode > ${HOME}/firebase-key.json
        gcloud auth activate-service-account --key-file=${HOME}/firebase-key.json
        gcloud --quiet config set project <your-firebase-project-id>
        gcloud auth application-default login

    - name: Configure Firebase
      run: |
        echo "SECRET_KEY_FOR_FIREBASE=$(echo ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY_BASE64 }} | base64 --decode)" > .env

    - name: Start Firebase emulators
      run: |
        firebase emulators:start 
        sleep 10  # Give the emulator time to start

    - name: Check one endpoint
      run: |
        curl -X POST http://localhost:5001/simplitracapp/us-central1/create_new_user -H "Content-Type: application/json" -d '{"key1":"value1", "key2":"value2"}'

    - name: Stop Firebase emulators
      run: |
        kill $firebase_pid