name: Firestore Action

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  firestore:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd functions
        pip install -r requirements.txt

    - name: Install Firebase CLI
      run: curl -sL https://firebase.tools | bash

    - name: Configure Firebase
      run: |
        echo "SECRET_KEY_FOR_FIREBASE=${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > .env

    - name: Start Firebase emulators
      run: |
        firebase emulators:start
        firebase_pid=$!
        sleep 10  # Give the emulator time to start


    - name: Check one endpoint
      run: |
        curl -X POST http://localhost:5001/simplitracapp/us-central1/create_new_user -H "Content-Type: application/json" -d '{"key1":"value1", "key2":"value2"}'

    - name: Stop Firebase emulators
      run: |
        kill $firebase_pid
